FROM busybox
MAINTAINER Andrey Murzich (andrey_murzich@epam.com)
ADD https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war /opt/apache-tomcat-8.5.24/webapps/sample.war
VOLUME /opt/apache-tomcat-8.5.24/webapps